In [2]:
print ('Hello World!')

Hello World!


#--Sky

In [13]:
name=input('enter your name....')

enter your name....Ahmed Nour


In [25]:
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")


a and b are equal


In [27]:
i = 1
while i < 10:
  print(i)
  i += 1

1
2
3
4
5
6
7
8
9


In [28]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


In [33]:
for x in range(10):
  print(x)

0
1
2
3
4
5
6
7
8
9


In [34]:
for x in range(2, 30, 3):
  print(x)

2
5
8
11
14
17
20
23
26
29


In [35]:
for x in range(6):
  print(x)
else:
  print("Finally finished!")

0
1
2
3
4
5
Finally finished!


In [37]:
def sum(x,y):
  return y * x

print(my_function(5,3)) 

15


In [38]:
cars = ["Ford", "Volvo", "BMW"]
for x in cars:
  print(x)

Ford
Volvo
BMW


In [39]:
cars.append("Honda")


In [42]:
for x in cars:
  print(x)

Ford
BMW
Honda


In [41]:
cars.pop(1)


'Volvo'

In [43]:
for x in cars:
  print(x)

Ford
BMW
Honda


In [45]:
cars.append("Honda")


In [47]:
for x in cars:
  print(x)

Ford
BMW
Honda
Honda
Honda


In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


%matplotlib inline

UsageError: unrecognized arguments: inline


In [10]:
arr1=np.array([1,2,3])
arr1.shape

(3,)

In [11]:
arr2=np.array([[1,2,3],[5,6,7]])
arr2.shape

(2, 3)

In [15]:
arr2.T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [20]:
arr1.sum()
arr2.sum()

24

In [21]:
z=np.zeros((2,3))
print(z)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [26]:
ones=np.ones((2,3))
print(ones)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [28]:
eye=np.eye((5))
print(eye)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [39]:
rnd=np.random.randn(10,3)
print(rnd)

[[-0.67821509 -0.59450204  0.39343993]
 [-0.80371101  1.74658963  1.50182787]
 [-0.4763209  -0.49468096 -0.63866032]
 [-1.59699619  1.07219008  1.36347448]
 [ 0.84975507  0.24561622 -1.04281545]
 [-0.69480503  0.41076905 -0.36280795]
 [ 0.54994258  2.09991655 -0.18590827]
 [-0.1729346   1.13951547 -1.02920719]
 [-0.67864846 -2.00092604 -0.72417569]
 [ 0.41011776 -0.93831903  0.58887089]]
