In [3]:
import pandas as pd
import numpy as np
import sklearn.linear_model as lm
import sklearn.model_selection as ms


In [4]:
data = pd.read_csv(r'D:\issr\CS 602\ISSR-CS602-Machine-Learning\Lab 6\gender.csv')
data.head(10)

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
5  0.132786  0.079557  0.119090  0.067958  0.209592  0.141634   1.932562   
6  0.150762  0.074463  0.160106  0.092899  0.205718  0.112819   1.530643   
7  0.160514  0.076767  0.144337  0.110532  0.231962  0.121430   1.397156   
8  0.142239  0.078018  0.138587  0.088206  0.208587  0.120381   1.099746   
9  0.134329  0.080350  0.121451  0.075580  0.201957  0.126377   1.190368   

          kurt    sp.ent       sfm  ...    centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...    0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...    0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...    0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...    0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...    0.135120  0.106398  0.016931   
5     8.308895  0.963181  0.738307  ...    0.132786  0.110132  0.017112   
6     5.987498  0.967573  0.762638  ...    0.150762  0.105945  0.026230   
7     4.766611  0.959255  0.719858  ...    0.160514  0.093052  0.017758   
8     4.070284  0.970723  0.770992  ...    0.142239  0.096729  0.017957   
9     4.787310  0.975246  0.804505  ...    0.134329  0.105881  0.019300   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  
5  0.253968  0.298222  0.007812  2.726562  2.718750  0.125160   male  
6  0.266667  0.479620  0.007812  5.312500  5.304688  0.123992   male  
7  0.144144  0.301339  0.007812  0.539062  0.531250  0.283937   male  
8  0.250000  0.336476  0.007812  2.164062  2.156250  0.148272   male  
9  0.262295  0.340365  0.015625  4.695312  4.679688  0.089920   male  

[10 rows x 21 columns]

In [10]:
X=data.iloc[:,:-1]# [rows,cols]  without last col
y=data.iloc[:,-1]# [rows,cols] last col only

In [15]:
from sklearn.preprocessing import StandardScaler

In [18]:
s=StandardScaler()
xs=s.fit_transform(X)

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
e=LabelEncoder()
y_endcoded=e.fit_transform(y)

In [22]:
y_endcoded

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [24]:
from sklearn.model_selection import cross_val_score,cross_val_predict

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
knn=KNeighborsClassifier()

In [27]:
score=cross_val_score(knn,xs,y_endcoded,cv=5,)

In [28]:
score

array([0.9148265 , 0.9384858 , 0.97003155, 0.97318612, 0.92563291])

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
tree=DecisionTreeClassifier(criterion='entropy')

In [48]:
score=cross_val_score(tree,xs,y_endcoded,cv=10)
score

array([0.91509434, 0.92138365, 0.97484277, 0.94025157, 0.96518987,
       0.98734177, 0.99050633, 0.97151899, 0.92405063, 0.97151899])

In [46]:
score.mean()

0.9555369795398455

In [63]:
y_predict=cross_val_predict(knn,xs,y_endcoded,cv=10)
from sklearn.metrics import confusion_matrix,f1_score
print(conf)
print(f1_score(y_endcoded,y_predict))

[[1521   63]
 [  76 1508]]
0.9540372670807453


0.9540372670807453

In [64]:
y_predict=cross_val_predict(tree,xs,y_endcoded,cv=10)
conf=confusion_matrix(y_endcoded,y_predict)
print(conf)
print(f1_score(y_endcoded,y_predict))

[[1520   64]
 [  72 1512]]
0.9569620253164557
